# Generated by Django 5.1.1 on 2024-09-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('sname', models.CharField(max_length=50)),
                ('fee', models.IntegerField()),
                ('marks', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
